import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../cashier/cashier_page.dart';
import '../reports/reports_page.dart';
import '../transactions/transactions_page.dart';

class HomePage extends StatefulWidget { const HomePage({super.key,required this.demoMode}); final bool demoMode; @override State<HomePage> createState()=>_HomePageState(); }
class _HomePageState extends State<HomePage>{int index=0;@override Widget build(BuildContext context){final pages=[_Dashboard(demoMode:widget.demoMode),const TransactionsPage(),const CashierPage(),const ReportsPage()];const titles=['Dashboard','Transaksi','Kasir','Laporan'];return Scaffold(appBar:AppBar(title:Text(titles[index]),actions:widget.demoMode?[const Padding(padding:EdgeInsets.only(right:12),child:Center(child:Chip(label:Text('MODE DEMO'))))]:null),body:IndexedStack(index:index,children:pages),bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(v)=>setState(()=>index=v),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard_outlined),selectedIcon:Icon(Icons.dashboard),label:'Dashboard'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),selectedIcon:Icon(Icons.receipt_long),label:'Transaksi'),NavigationDestination(icon:Icon(Icons.point_of_sale_outlined),selectedIcon:Icon(Icons.point_of_sale),label:'Kasir'),NavigationDestination(icon:Icon(Icons.bar_chart_outlined),selectedIcon:Icon(Icons.bar_chart),label:'Laporan')]));}}
class _Dashboard extends StatelessWidget{const _Dashboard({required this.demoMode});final bool demoMode;@override Widget build(BuildContext context){final f=NumberFormat.currency(locale:'id_ID',symbol:'Rp ',decimalDigits:0);final cards=[('Omzet Hari Ini','Rp 3.250.000',Icons.payments_outlined),('Transaksi','18',Icons.receipt_long_outlined),('Kasbon Aktif','7',Icons.credit_score_outlined),('Saldo Kas','Rp 12.750.000',Icons.account_balance_wallet_outlined)];return RefreshIndicator(onRefresh:() async=>Future<void>.delayed(const Duration(milliseconds:300)),child:ListView(padding:const EdgeInsets.all(16),children:[const Text('IRKOP Konter',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:4),Text(demoMode?'Data simulasi untuk pengembangan':'Data operasional outlet'),const SizedBox(height:16),GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:cards.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.28),itemBuilder:(_,i){final c=cards[i];return Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(c.$3),const Spacer(),Text(c.$1),Text(c.$2,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))])));}),const SizedBox(height:20),const Text('Transaksi Terbaru',style:TextStyle(fontWeight:FontWeight.bold,fontSize:18)),...List.generate(8,(i)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.receipt)),title:Text('TRX-DEMO-${1008 - i}'),subtitle:Text(i.isEven?'Tunai • Selesai':'Transfer • Terkonfirmasi'),trailing:Text(f.format(75000+i*125000)))))]));}}
