-- IRKOP Cell Supabase bootstrap migration. Audit existing IRKOP schema before execution.
create extension if not exists pgcrypto;
create table if not exists public.irkop_cell_businesses (id uuid primary key default gen_random_uuid(), owner_user_id uuid not null references auth.users(id) on delete cascade, name text not null, created_at timestamptz not null default now());
create table if not exists public.irkop_cell_outlets (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.irkop_cell_businesses(id) on delete cascade, name text not null, address text, timezone text not null default 'Asia/Jakarta', created_at timestamptz not null default now());
create table if not exists public.irkop_cell_products (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.irkop_cell_businesses(id) on delete cascade, name text not null, category text, sku text, sell_price numeric(14,2) not null check(sell_price>=0), stock numeric(14,2) not null default 0, is_active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.irkop_cell_customers (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.irkop_cell_businesses(id) on delete cascade, name text not null, phone text, created_at timestamptz not null default now());
create table if not exists public.irkop_cell_transactions (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.irkop_cell_businesses(id) on delete cascade, outlet_id uuid not null references public.irkop_cell_outlets(id), customer_id uuid references public.irkop_cell_customers(id), transaction_no text not null, payment_method text not null check(payment_method in ('cash','transfer','credit','cash_tunai')), status text not null default 'completed' check(status in ('pending','completed','cancelled')), total numeric(14,2) not null check(total>=0), transaction_at timestamptz not null default now(), manual_entry boolean not null default false, created_at timestamptz not null default now(), unique(business_id,transaction_no));
create table if not exists public.irkop_cell_transaction_items (id uuid primary key default gen_random_uuid(), transaction_id uuid not null references public.irkop_cell_transactions(id) on delete cascade, product_id uuid references public.irkop_cell_products(id), product_name text not null, qty numeric(14,2) not null check(qty>0), unit_price numeric(14,2) not null check(unit_price>=0), subtotal numeric(14,2) not null check(subtotal>=0));
create table if not exists public.irkop_cell_cash_mutations (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.irkop_cell_businesses(id) on delete cascade, outlet_id uuid references public.irkop_cell_outlets(id), transaction_id uuid references public.irkop_cell_transactions(id), mutation_type text not null check(mutation_type in ('in','out','reversal')), amount numeric(14,2) not null check(amount>=0), description text, occurred_at timestamptz not null default now());
create table if not exists public.irkop_cell_device_slots (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.irkop_cell_businesses(id) on delete cascade, device_fingerprint text not null, device_name text, platform text, is_active boolean not null default true, last_seen_at timestamptz, created_at timestamptz not null default now(), unique(business_id,device_fingerprint));
alter table public.irkop_cell_businesses enable row level security;
alter table public.irkop_cell_outlets enable row level security;
alter table public.irkop_cell_products enable row level security;
alter table public.irkop_cell_customers enable row level security;
alter table public.irkop_cell_transactions enable row level security;
alter table public.irkop_cell_transaction_items enable row level security;
alter table public.irkop_cell_cash_mutations enable row level security;
alter table public.irkop_cell_device_slots enable row level security;
create policy "owner manages own business" on public.irkop_cell_businesses for all to authenticated using(owner_user_id=auth.uid()) with check(owner_user_id=auth.uid());
-- Child-table policies must be mapped to the existing IRKOP tenant model; do not make them public.
